[package]
name = "nu-mcp"
version = "0.3.8"
description = ""
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
rmcp-macros = "0.8.5"
schemars = "1.0.4"
serde_json = "1.0.145"

[dependencies.tokio]
version = "1.48.0"
features = ["full"]

[dependencies.rmcp]
version = "0.8.5"
features = ["transport-io"]

[dependencies.serde]
version = "1.0.228"
features = ["derive"]

[dependencies.clap]
version = "4.5.51"
features = ["derive"]

[dev-dependencies]
tokio-util = "0.7.17"
